"use client";
import {useState} from "react";import Link from "next/link";import {ArrowLeft,BrainCircuit,Gauge,Play,TriangleAlert} from "lucide-react";
import type {WingBoxInput,StructuralResult} from "@/lib/structural";
type Candidate={input:WingBoxInput;result:StructuralResult};
const initial:WingBoxInput={span:600,chord:180,height:90,skin:2.0,spar:3.0,rib:2.0,ribCount:5,material:"aluminum",lift:2200,tipForce:350,bendingMoment:120000,torque:85000,safetyFactor:1.5};
export default function Structural(){const[p,setP]=useState(initial);const[result,setResult]=useState<{baseline:StructuralResult;candidates:Candidate[]}>();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const num=(k:keyof WingBoxInput)=>(e:React.ChangeEvent<HTMLInputElement>)=>setP({...p,[k]:Number(e.target.value)});
 async function run(){setBusy(true);setError("");try{const r=await fetch("/api/structural",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Structural analysis failed.");setResult(j)}catch(e){setError(e instanceof Error?e.message:"Analysis failed.")}finally{setBusy(false)}}
 return <main className="designPage"><header className="designHeader"><Link href="/"><ArrowLeft/> Workspace</Link><div><b>THIN-WALL STRUCTURAL OPTIMIZER</b><span>Load-carrying skin · Wing-box research demonstrator</span></div><div className="researchBadge"><BrainCircuit/> SCREENING PHYSICS</div></header>
 <section className="structHero"><p className="eyebrow">AEROSPACE LIGHTWEIGHTING PROBLEM</p><h1>Carry more load with less structural mass.</h1><p>The skin participates in carrying bending, shear and torsion while spars and ribs stabilize and redistribute load. This demonstrator searches lower-mass thin-wall configurations before metal-AM manufacturability optimization.</p></section>
 <div className="designGrid"><section className="designForm"><h2>Wing-box design space</h2><div className="fieldGrid">
 {([["span","Span (mm)"],["chord","Chord (mm)"],["height","Box height (mm)"],["skin","Skin thickness (mm)"],["spar","Spar thickness (mm)"],["rib","Rib thickness (mm)"],["ribCount","Rib count"],["lift","Distributed lift resultant (N)"],["tipForce","Tip force (N)"],["bendingMoment","Applied root moment (N·mm)"],["torque","Torsional moment (N·mm)"],["safetyFactor","Screening safety factor"]] as [keyof WingBoxInput,string][]).map(([k,l])=><label key={k}>{l}<input type="number" step="any" value={p[k] as number} onChange={num(k)}/></label>)}
 <label>Material<select value={p.material} onChange={e=>setP({...p,material:e.target.value as WingBoxInput["material"]})}><option value="aluminum">Aluminum research profile</option><option value="titanium">Titanium research profile</option></select></label></div>
 <div className="safetyNote"><TriangleAlert/>Static-equivalent analytical screening only. It does not replace shell FEA, buckling, fatigue/dynamics, approved material allowables or physical test validation.</div>
 <button className="primary wide" onClick={run} disabled={busy}><Play/>{busy?"SOLVING + OPTIMIZING…":"ANALYZE LOAD PATH + OPTIMIZE MASS"}</button>{error&&<div className="analysisError">{error}</div>}</section>
 <section className="designResults"><h2>Structural result</h2>{!result?<div className="emptyResults"><Gauge/><b>Ready for load case</b><span>Run the baseline to generate structural utilization and lightweight candidates.</span></div>:<><div className="resultScore"><span>BASELINE MASS</span><b>{result.baseline.massKg.toFixed(3)} kg</b><em>{Math.round(result.baseline.skinMassFraction*100)}% in load-carrying skin</em></div><div className="structMetrics"><div><small>COMBINED STRESS</small><b>{result.baseline.combinedStressMPa.toFixed(1)} MPa</b></div><div><small>ROOT BENDING</small><b>{result.baseline.rootBendingStressMPa.toFixed(1)} MPa</b></div><div><small>TORSIONAL SHEAR</small><b>{result.baseline.torsionalShearMPa.toFixed(1)} MPa</b></div><div><small>TIP DEFLECTION</small><b>{result.baseline.tipDeflectionMm.toFixed(2)} mm</b></div><div><small>UTILIZATION</small><b>{(result.baseline.utilization*100).toFixed(0)}%</b></div></div><h3 className="candidateTitle">Lowest-mass screened candidates</h3><div className="candidateList">{result.candidates.map((c,i)=><article key={i}><strong>#{i+1} · {c.result.massKg.toFixed(3)} kg</strong><span>Skin {c.input.skin} mm · Spar {c.input.spar} mm · {c.input.ribCount} ribs</span><span>Utilization {(c.result.utilization*100).toFixed(0)}% · Δ {(c.result.tipDeflectionMm).toFixed(2)} mm</span></article>)}</div><div className="analysisAssumptions"><strong>Required next validation layers</strong>{result.baseline.recommendations.map(x=><span key={x}>• {x}</span>)}{result.baseline.assumptions.map(x=><span key={x}>• {x}</span>)}</div></>}</section></div></main>}