"use client";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Box, CheckCircle2, ChevronRight, FileUp, Gauge, Layers3, Settings2, ShieldCheck, TriangleAlert, Sparkles, Play, Activity } from "lucide-react";
import { DEMO_PART, DEMO_STL_URL } from "@/lib/demo";
import type { AnalysisResult } from "@/lib/types";
const ModelViewer=dynamic(()=>import("@/components/ModelViewer"),{ssr:false});

type Check={name:string,status:"pass"|"review",detail:string};
const materials=["Ti-6Al-4V","Inconel 718","AlSi10Mg","316L Stainless Steel"];
const processes=["Laser Powder Bed Fusion","Electron Beam Powder Bed Fusion","Directed Energy Deposition"];
export default function Home(){
 const [file,setFile]=useState<File>(); const [demo,setDemo]=useState(false); const [material,setMaterial]=useState(materials[0]); const [process,setProcess]=useState(processes[0]); const [analysis,setAnalysis]=useState<AnalysisResult>(); const [analyzing,setAnalyzing]=useState(false); const [analysisError,setAnalysisError]=useState("");
 const url=useMemo(()=>file?URL.createObjectURL(file):demo?DEMO_STL_URL:undefined,[file,demo]);
 useEffect(()=>()=>{if(file&&url?.startsWith("blob:"))URL.revokeObjectURL(url)},[file,url]);
 const hasModel=Boolean(file||demo);
 async function runAnalysis(){setAnalyzing(true);setAnalysisError("");setAnalysis(undefined);try{if(!demo){throw new Error("Uploaded-STL geometry extraction is the next analysis module. Load the built-in demo to run the current validated intent analysis.")}const res=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(DEMO_PART)});if(!res.ok)throw new Error("Analysis service returned an error.");setAnalysis(await res.json())}catch(e){setAnalysisError(e instanceof Error?e.message:"Analysis failed.")}finally{setAnalyzing(false)}}
 const checks:Check[]=hasModel?[{name:"Mesh integrity",status:"pass",detail:"STL loaded successfully"},{name:"Build orientation",status:"review",detail:"Orientation optimization required"},{name:"Support strategy",status:"review",detail:"Analyze overhang regions before release"},{name:"Process compatibility",status:"pass",detail:`${material} profile available for review`}]:[];
 return <main><header><div className="brand"><div className="mark">VT</div><div><strong>AM First-Time Quality</strong><span>Senior Design · Metallic Additive Manufacturing</span></div></div><div style={{display:"flex",alignItems:"center",gap:16}}><Link className="back" href="/design"><Sparkles/>Generative CAD</Link><div className="status"><span></span>Prototype Workspace</div></div></header>
 <section className="hero"><div><p className="eyebrow">BUILD PREPARATION WORKSPACE</p><h1>From CAD geometry to a more confident metal AM build.</h1><p>Inspect geometry, configure the manufacturing process, identify build risks, and document recommendations before printer release.</p></div><div className="score"><Gauge/><div><small>BUILD READINESS</small><b>{analysis?analysis.readiness:hasModel?(demo?"70":"62"):"—"}<i>{hasModel?"%":""}</i></b><span>{analysis?`${analysis.risk} risk · analysis complete`:hasModel?"Engineering review required":"Upload or load the demo part"}</span></div></div></section>
 <nav className="steps">{["Model","Process","Analyze","Optimize","Validate","Export"].map((x,i)=>{const done=(i===0&&hasModel)||(i===1&&hasModel)||(i===2&&Boolean(analysis));const active=(i===0&&!hasModel)||(i===2&&hasModel&&!analysis);const planned=i>2;return <div className={done?"done":active?"active":planned?"planned":""} title={planned?"Planned phase — not yet implemented in this prototype":undefined} key={x}><span>{done?"✓":i+1}</span>{x}{planned&&<small>PLANNED</small>}<ChevronRight/></div>})}</nav>
 <div className="workspace"><section className="mainPanel"><div className="panelTitle"><div><Box/><div><h2>Build Model</h2><p>STL geometry inspection and preparation</p></div></div>{hasModel&&<button className="secondary" onClick={()=>{setFile(undefined);setDemo(false);setAnalysis(undefined);setAnalysisError("")}}>Replace model</button>}</div>
 {!hasModel?<label className="drop"><FileUp/><h3>Upload an STL model</h3><p>Choose a non-sensitive test part to start the build analysis.</p><span>SELECT STL</span><input type="file" accept=".stl" onChange={e=>{setDemo(false);setAnalysis(undefined);setAnalysisError("");setFile(e.target.files?.[0])}}/><button type="button" className="demoButton" onClick={e=>{e.preventDefault();setFile(undefined);setDemo(true);setMaterial("Ti-6Al-4V");setProcess("Laser Powder Bed Fusion");setAnalysis(undefined);setAnalysisError("")}}><Play/> LOAD AEROSPACE DEMO PART</button></label>:<><ModelViewer url={url}/><div className="filebar"><div><Layers3/><span><b>{demo?DEMO_PART.name:file?.name}</b><small>{demo?"Synthetic aerospace-style test article · Ti-6Al-4V · LPBF":`${((file?.size||0)/1048576).toFixed(2)} MB · STL`}</small></span></div><span className="loaded"><CheckCircle2/>Loaded</span></div></>}
 </section><aside><section className="card"><div className="cardTitle"><Settings2/><div><h3>Process Configuration</h3><p>Preliminary engineering inputs</p></div></div><label>Material<select value={material} onChange={e=>setMaterial(e.target.value)}>{materials.map(x=><option key={x}>{x}</option>)}</select></label><label>AM Process<select value={process} onChange={e=>setProcess(e.target.value)}>{processes.map(x=><option key={x}>{x}</option>)}</select></label><label>Machine Profile<select><option>Generic research machine</option></select></label><div className="notice"><ShieldCheck/><span><b>Research mode</b>Machine-specific parameters require validated printer profiles.</span></div></section>
 <section className="card"><div className="cardTitle"><TriangleAlert/><div><h3>Preflight Checks</h3><p>{hasModel?"Initial screening results":"Waiting for geometry"}</p></div></div>{checks.length?checks.map(c=><div className={"check "+c.status} key={c.name}>{c.status==="pass"?<CheckCircle2/>:<TriangleAlert/>}<span><b>{c.name}</b><small>{c.detail}</small></span></div>):<div className="empty">Upload an STL to populate engineering checks.</div>}<button className="primary" disabled={!hasModel||analyzing} onClick={runAnalysis}>{analyzing?"ANALYZING…":"RUN FULL ANALYSIS"}</button>{analysisError&&<div className="analysisError">{analysisError}</div>}</section></aside></div>
 {analysis&&<section className="analysisPanel"><div className="analysisHeader"><div><p className="eyebrow">ANALYSIS COMPLETE</p><h2>First-Time Quality Engineering Review</h2><p>Deterministic prototype analysis for the synthetic demo article. Recommendations remain engineering decision support.</p></div><div className="analysisScore"><small>READINESS</small><b>{analysis.readiness}%</b><span className={"risk "+analysis.risk.toLowerCase()}>{analysis.risk} RISK</span></div></div><div className="metricGrid"><div><small>BUILD ENVELOPE</small><b>{analysis.metrics.dimensions.x} × {analysis.metrics.dimensions.y} × {analysis.metrics.dimensions.z} mm</b></div><div><small>NOMINAL VOLUME</small><b>{(analysis.metrics.volume/1000).toFixed(1)} cm³</b></div><div><small>SURFACE AREA</small><b>{(analysis.metrics.surfaceArea/100).toFixed(1)} cm²</b></div><div><small>ASPECT RATIO</small><b>{analysis.metrics.aspectRatio.toFixed(2)}</b></div></div><div className="analysisRecommendations">{analysis.recommendations.map(r=><article key={r.id} className={r.severity}><div><span>{r.category.toUpperCase()}</span><i>{Math.round(r.confidence*100)}% confidence</i></div><h3>{r.title}</h3><p>{r.rationale}</p><strong>RECOMMENDED ACTION</strong><p>{r.action}</p></article>)}</div><div className="analysisAssumptions"><strong>Analysis basis · {analysis.modelVersion}</strong>{analysis.assumptions.map(a=><span key={a}>• {a}</span>)}</div></section>}
 <footer><span>Virginia Tech Senior Design · Engineering prototype</span><span>Recommendations require validation before manufacturing use.</span></footer></main>}