import {AnalysisResult,GeometryMetrics,PartIntent,Recommendation} from "./types";
export function analyzeIntent(p:PartIntent):AnalysisResult{
 const volume=p.length*p.width*p.height; const area=2*(p.length*p.width+p.length*p.height+p.width*p.height); const minDim=Math.min(p.length,p.width,p.height); const maxDim=Math.max(p.length,p.width,p.height);
 const metrics:GeometryMetrics={volume,surfaceArea:area,dimensions:{x:p.length,y:p.width,z:p.height},triangleCount:12,aspectRatio:maxDim/minDim,thinWallRisk:p.wall<1};
 const r:Recommendation[]=[];
 if(p.wall<1.2)r.push({id:"wall",category:"geometry",severity:"high",title:"Thin-wall manufacturing risk",rationale:`${p.wall.toFixed(2)} mm nominal wall may be sensitive to process capability, orientation and distortion.`,action:"Increase wall thickness or validate the feature using a representative coupon/build study.",confidence:.9});
 if(p.height>p.length*.8)r.push({id:"orient",category:"orientation",severity:"medium",title:"Evaluate lower build-height orientation",rationale:"Current envelope suggests build time and thermal accumulation may improve with an alternate orientation.",action:"Compare candidate orientations for height, support volume, critical surfaces and recoater risk.",confidence:.76});
 if(p.holeDiameter<3)r.push({id:"hole",category:"geometry",severity:"medium",title:"Small internal feature requires compensation study",rationale:"Small as-built holes can be sensitive to orientation, contour strategy and powder removal.",action:"Flag the hole as CTQ and plan machining/reaming or empirical compensation if required.",confidence:.82});
 r.push({id:"support",category:"support",severity:"medium",title:"Generate support candidates",rationale:"Metal AM support decisions affect heat transfer, distortion, surface condition and removability.",action:"Score support candidates against thermal anchoring, accessibility, critical surfaces and material usage.",confidence:.88});
 r.push({id:"inspect",category:"inspection",severity:"low",title:"Create a first-article inspection plan",rationale:"First-time quality requires verification of CTQ dimensions and relevant material/defect requirements.",action:"Map each requirement to an inspection method and retain results with the build record.",confidence:.95});
 const penalty=r.reduce((s,x)=>s+(x.severity==="high"?18:x.severity==="medium"?9:3),0); return {readiness:Math.max(25,100-penalty),risk:r.some(x=>x.severity==="high")?"HIGH":r.some(x=>x.severity==="medium")?"MEDIUM":"LOW",metrics,recommendations:r,assumptions:["Dimensions are interpreted in millimeters.","Results are decision support, not a qualified manufacturing procedure.","No machine-specific parameter set has been validated."],modelVersion:"FTQ-rule-engine-0.1"};
}